REGISTRY = {
    # --- Catalog & Metadata Resolvers ---
    "get_providers": {
        "description": "List all available GPU cloud providers (e.g. runpod, novita). Use to discover or resolve the provider param.",
        "category": "resolver",
        "method": "GET",
        "path_template": "/providers",
        "path_params": [],
        "query_params": [],
        "requires": [],
        "produces": ["providers"],
        "resolver_for": ["provider"],
        "response_list_key": "providers",
        "selection_strategy": "requires_selection",
        "cost_incurring": False,
        "destructive": False,
    },
    "get_all_gpus": {
        "description": "List ALL GPUs across every provider with prices. Use when user asks for best/cheapest/recommended GPU or compares across providers. The reasoning node filters/ranks the result.",
        "category": "resolver",
        "method": "GET",
        "path_template": "/gpus",
        "path_params": [],
        "query_params": [],
        "requires": [],
        "produces": ["gpus"],
        "resolver_for": ["gpu_name", "gpu_id", "hourly_price"],
        "response_list_key": "gpus",
        "selection_strategy": "requires_selection",
        "cost_incurring": False,
        "destructive": False,
    },
    "get_provider_gpus": {
        "description": "List GPUs for ONE specific provider. Use when provider is explicitly stated. Returns real gpu_id values needed for create_pod.",
        "category": "resolver",
        "method": "GET",
        "path_template": "/gpus/{provider}",
        "path_params": ["provider"],
        "query_params": [],
        "requires": ["provider"],
        "produces": ["gpus"],
        "resolver_for": ["gpu_name", "gpu_id"],
        "response_list_key": "gpus",
        "selection_strategy": "requires_selection",
        "cost_incurring": False,
        "destructive": False,
    },
    "get_provider_gpu_availability": {
        "description": "List real-time GPU availability slots for a provider. Returns product_id / gpu_id values suitable for pod creation on Novita.",
        "category": "resolver",
        "method": "GET",
        "path_template": "/{provider}/gpu_availability",
        "path_params": ["provider"],
        "query_params": [],
        "requires": ["provider"],
        "produces": ["gpu_availability"],
        "resolver_for": ["gpu_id", "product_id"],
        "response_list_key": "gpu_availability",
        "selection_strategy": "requires_selection",
        "cost_incurring": False,
        "destructive": False,
    },
    "get_gpu_metadata": {
        "description": "Fetch detailed metadata for ONE specific GPU by its exact gpu_id. Only use when gpu_id is already known from a previous lookup.",
        "category": "resolver",
        "method": "GET",
        "path_template": "/{provider}/gpu_metadata",
        "path_params": ["provider"],
        "query_params": ["gpu_id"],
        "requires": ["provider", "gpu_id"],
        "produces": ["gpu"],
        "response_list_key": None,
        "selection_strategy": "single",
        "cost_incurring": False,
        "destructive": False,
    },

    # --- Pod Operations ---
    "get_user_pods": {
        "description": "List all running/stopped pods owned by the user for a given provider. Used to resolve pod_id before start/stop/delete operations.",
        "category": "resolver",
        "method": "GET",
        "path_template": "/{provider}/user_pods",
        "path_params": ["provider"],
        "query_params": [],
        "requires": ["provider"],
        "produces": ["pods"],
        "resolver_for": ["pod_id"],
        "response_list_key": "pods",
        "selection_strategy": "requires_selection",
        "cost_incurring": False,
        "destructive": False,
    },
    "get_user_pod": {
        "description": "Fetch details of ONE specific pod by its exact pod_id.",
        "category": "resolver",
        "method": "GET",
        "path_template": "/{provider}/user_pod/{pod_id}",
        "path_params": ["provider", "pod_id"],
        "query_params": [],
        "requires": ["provider", "pod_id"],
        "produces": ["pod"],
        "response_list_key": None,
        "selection_strategy": "single",
        "cost_incurring": False,
        "destructive": False,
    },
    "create_pod": {
        "description": (
            "Deploy / create / launch / spin up a new GPU pod. Trigger words: deploy, create, launch, spin up, start a pod. "
            "Requires provider, a user-chosen name, and a real gpu_id. "
            "ALWAYS resolve gpu_id via get_gpu_catalog or get_pod_context — never accept a raw model name."
        ),
        "category": "create",
        "method": "POST",
        "path_template": "/{provider}/create_pod",
        "path_params": ["provider"],
        "query_params": [
            "name", "gpu_id", "image_name", "gpu_count",
            "container_disk_gb", "volume_gb", "volume_mount_path",
            "network_volume_id", "vcpu_count"
        ],
        "requires": ["provider", "name", "gpu_id"],
        "produces": ["pod"],
        "cost_incurring": True,
        "destructive": False,
        # gpu_id must be resolved from get_gpu_catalog — user text is never a valid api gpu_id
        "api_lookup_params": ["gpu_id"],
    },
    "start_pod": {
        "description": "Start (resume) an existing stopped pod. Requires the real pod_id from get_user_pods.",
        "category": "action",
        "method": "POST",
        "path_template": "/{provider}/start_pod/{pod_id}",
        "path_params": ["provider", "pod_id"],
        "query_params": [],
        "requires": ["provider", "pod_id"],
        "produces": ["result"],
        "cost_incurring": True,
        "destructive": False,
    },
    "stop_pod": {
        "description": "Stop a running pod (keeps it billed at storage rate). Requires the real pod_id.",
        "category": "action",
        "method": "POST",
        "path_template": "/{provider}/stop_pod/{pod_id}",
        "path_params": ["provider", "pod_id"],
        "query_params": [],
        "requires": ["provider", "pod_id"],
        "produces": ["result"],
        "cost_incurring": False,
        "destructive": True,
    },
    "delete_pod": {
        "description": "Permanently delete a pod. Requires the real pod_id from get_user_pods. This is irreversible.",
        "category": "action",
        "method": "DELETE",
        "path_template": "/{provider}/delete_pod/{pod_id}",
        "path_params": ["provider", "pod_id"],
        "query_params": [],
        "requires": ["provider", "pod_id"],
        "produces": ["result"],
        "cost_incurring": False,
        "destructive": True,
    },

    # --- Volume Operations ---
    "get_user_volumes": {
        "description": "List all network volumes owned by the user for a provider. Used to resolve volume_id before delete operations.",
        "category": "resolver",
        "method": "GET",
        "path_template": "/{provider}/user_volumes",
        "path_params": ["provider"],
        "query_params": [],
        "requires": ["provider"],
        "produces": ["volumes"],
        "resolver_for": ["volume_id"],
        "response_list_key": "volumes",
        "selection_strategy": "requires_selection",
        "cost_incurring": False,
        "destructive": False,
    },
    "create_volume": {
        "description": "Create a new persistent network volume. Requires provider, datacenter_id (from get_datacenters), a name, and size in GB.",
        "category": "create",
        "method": "POST",
        "path_template": "/{provider}/create_volume",
        "path_params": ["provider"],
        "body_params": ["datacenter_id", "name", "size"],  # Pydantic JSON Body
        "requires": ["provider", "datacenter_id", "name", "size"],
        "produces": ["result"],
        "cost_incurring": True,
        "destructive": False,
        "api_lookup_params": ["datacenter_id"],
    },
    "delete_volume": {
        "description": "Permanently delete a network volume by its real volume_id. Irreversible.",
        "category": "action",
        "method": "DELETE",
        "path_template": "/{provider}/delete_volume/{volume_id}",
        "path_params": ["provider", "volume_id"],
        "query_params": [],
        "requires": ["provider", "volume_id"],
        "produces": ["result"],
        "cost_incurring": False,
        "destructive": True,
    },

    # --- Comprehensive Catalog (preferred for create workflows) ---
    "get_gpu_catalog": {
        "description": (
            "PREFERRED resolver for gpu_id. Returns ALL GPUs from all providers with API-ready gpu_id values "
            "(no provider prefix — plug directly into create_pod). Supports optional ?provider=runpod and "
            "?available_only=true query params. The LLM should use filter_hint to pick the best match."
        ),
        "category": "resolver",
        "method": "GET",
        "path_template": "/gpu_catalog",
        "path_params": [],
        "query_params": ["provider", "available_only"],
        "requires": [],
        "produces": ["gpus"],
        "resolver_for": ["gpu_id"],
        "response_list_key": "gpus",
        "selection_strategy": "requires_selection",
        "cost_incurring": False,
        "destructive": False,
    },
    "get_pod_context": {
        "description": (
            "Returns available deployable GPUs (API-ready gpu_ids) + user volumes + default params "
            "for ONE provider. Use to get everything needed for create_pod in one call."
        ),
        "category": "resolver",
        "method": "GET",
        "path_template": "/pod_context/{provider}",
        "path_params": ["provider"],
        "query_params": [],
        "requires": ["provider"],
        "produces": ["available_gpus", "user_volumes", "defaults"],
        "resolver_for": ["gpu_id"],
        "response_list_key": "available_gpus",
        "selection_strategy": "requires_selection",
        "cost_incurring": False,
        "destructive": False,
    },
    "get_datacenters": {
        "description": "List all datacenter IDs for a provider. Use to resolve datacenter_id for create_volume.",
        "category": "resolver",
        "method": "GET",
        "path_template": "/{provider}/datacenters",
        "path_params": ["provider"],
        "query_params": [],
        "requires": ["provider"],
        "produces": ["datacenters"],
        "resolver_for": ["datacenter_id"],
        "response_list_key": "datacenters",
        "selection_strategy": "requires_selection",
        "cost_incurring": False,
        "destructive": False,
    },
}



